version: '3.8'

services:
  postgres: 
    image: postgres  #hub.docker.com
    ports: 
     - '5432:5432'

    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 
        POSTGRES_DB: review

  redis: 
    image: redis
    ports: 
     - '6379:6379'
    
     
